# Generated by Django 4.1.5 on 2023-02-14 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='General title of the task.', max_length=150, verbose_name='Título')),
                ('description', models.TextField(help_text='Text that explains more details about the task.', verbose_name='Descrição')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('deadline_date', models.DateTimeField(help_text='Task expiration date/time.', verbose_name='Data prazo')),
                ('date_conclusion', models.DateTimeField(auto_now=True, verbose_name='Data de conclusão')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('punctuality', models.BooleanField(default=False, verbose_name='Pontualidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
